[package]
name = "malstrom"
version = "0.1.0"
edition = "2024"
description = "Malstrom is a distributed, stateful stream processing framework written in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/MalstromDevelopers/malstrom"
readme = "../README.md"
categories = [
    "concurrency",
]
keywords = [
    "stream",
    "data",
    "framework",
    "streaming",
    "distributed",
]

[lints]
workspace = true

[dependencies]
itertools = "0.11.0"
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "1.0.49"
tracing = { version = "0.1.40", features = ["log"] }
indexmap = { version = "2.1.0", features = ["serde"] }

tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "rt", "sync", "time"] }
rmp-serde = "1.3.0"
seahash = "4.1.0"
bon = "3.3.2"
async-trait = "0.1.85"
futures = "0.3.31"
flume = "0.11.1"
malstrom-macros = { path = "../malstrom-macros"}
pin-project = "1.1.10"

[dev-dependencies]
tracing-subscriber = "0.3.18"
proptest = "1.5.0"
# for eventtime examples
chrono = { version = "0.4.41", features = ["serde"] }
# the extracted layers, used by the examples
malstrom-distributed = { path = "../malstrom-distributed" }
malstrom-operators = { path = "../malstrom-operators" }
malstrom-testkit = { path = "../malstrom-testkit" }
expiremap = { version="0.1.0-beta.3", features = ["serde"] }
console-subscriber = "0.5.0"
