name: Push Images to GHCR

on:
  push:
    branches:
      - 'main'
    paths:
      - 'malstrom-k8s/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push malstrom-k8s-operator
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: malstrom-k8s
          file: malstrom-k8s/malstrom-k8s-operator.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/malstrom-k8s-operator:latest,ghcr.io/malstromdevelopers/malstrom-k8s-operator:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and Push artifact-manager
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: malstrom-k8s/artifact-manager.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/artifact-manager:latest,ghcr.io/malstromdevelopers/artifact-manager:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and Push artifact-downloader
        uses: docker/build-push-action@v6
        with:
          context: malstrom-k8s
          file: malstrom-k8s/artifact-downloader.dockerfile
          push: true
          tags: ghcr.io/malstromdevelopers/artifact-downloader:latest,ghcr.io/malstromdevelopers/artifact-downloader:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
